PREDICT:
  device: cuda:0
  model_save_path: C:/Users/91703/Downloads/SuperRetina-main/SuperRetina-main/save/SuperRetina.pth
  model_image_width: 768
  model_image_height: 768
  use_matching_trick: True

  nms_size: 10
  nms_thresh: 0.01

  knn_thresh: 0.9
  
